apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "doc-demo005"
  description: "wrwr"
  annotations:
    github.com/project-slug: "baobaoqiang/doc-demo005"
    backstage.io/techdocs-ref: github:https://github.com/baobaoqiang/doc-demo005
spec:
  type: documentation
  lifecycle: experimental
  owner: "wq"
